name: Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[release]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1

      - name: Build Library
        run: cargo build --release
